version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - forbidigo
    - govet
    - iface
    - ineffassign
    - misspell
    - nilnil
    - sloglint
    - unparam
    - unused
    - staticcheck
    - godot
  settings:
    iface:
      enable:
        - identical
    sloglint:
      attr-only: true
