ARG DISTROLESS_SHA="pass-a-valid-docker-sha-otherwise-this-will-fail"

FROM gcr.io/distroless/base@sha256:${DISTROLESS_SHA}
LABEL maintainer="signoz"
WORKDIR /usr/local/foundryctl

ARG OS="linux"
ARG ARCH

COPY ./target/${OS}-${ARCH}/foundryctl /usr/local/bin/foundryctl

ENTRYPOINT ["/usr/local/bin/foundryctl"]
