apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouse-operator
  labels:
    app.kubernetes.io/name: clickhouse-operator
    app.kubernetes.io/instance: clickhouse-operator
    app.kubernetes.io/version: "0.25.3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clickhouse-operator
subjects:
  - kind: ServiceAccount
    name: clickhouse-operator
    namespace: datastore
