# based on manfiest https://github.com/Altinity/clickhouse-operator/releases/download/release-0.25.3/altinity-clickhouse-operator-0.25.3.tgz
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datastore

resources:
- serviceaccount.yaml
- configmap.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- service.yaml
- deployment.yaml
