apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-operator
  labels:
    app.kubernetes.io/name: clickhouse-operator
    app.kubernetes.io/instance: clickhouse-operator
    app.kubernetes.io/version: "0.25.3"
