apiVersion: v1
kind: Service
metadata:
  name: clickhouse-operator-metrics
  labels:
    app.kubernetes.io/name: clickhouse-operator
    app.kubernetes.io/instance: clickhouse-operator
    app.kubernetes.io/version: "0.25.3"
spec:
  ports:
    - port: 8888
      name: ch-metrics
    - port: 9999
      name: op-metrics
  selector:
    app.kubernetes.io/name: clickhouse-operator
    app.kubernetes.io/instance: clickhouse-operator
