connectors:
  o11ymeter:
    dimensions:
    - name: service.name
    - name: deployment.environment
    - name: host.name
    metrics_flush_interval: 1h
exporters:
  clickhouselogsexporter:
    dsn: tcp://localhost:9000/o11y_logs
    sending_queue:
      enabled: false
    timeout: 45s
    use_new_schema: true
  clickhousetraces:
    datasource: tcp://localhost:9000/o11y_traces
    low_cardinal_exception_grouping: ${env:LOW_CARDINAL_EXCEPTION_GROUPING}
    sending_queue:
      enabled: false
    timeout: 45s
    use_new_schema: true
  o11yclickhousemeter:
    dsn: tcp://localhost:9000/o11y_meter
    sending_queue:
      enabled: false
    timeout: 45s
  o11yclickhousemetrics:
    dsn: tcp://localhost:9000/o11y_metrics
    sending_queue:
      enabled: false
    timeout: 45s
extensions:
  pprof:
    endpoint: 0.0.0.0:1777
  o11y_health_check:
    endpoint: 0.0.0.0:13133
processors:
  batch:
    send_batch_max_size: 25000
    send_batch_size: 20000
    timeout: 1s
  batch/meter:
    send_batch_max_size: 25000
    send_batch_size: 20000
    timeout: 1s
  o11yspanmetrics/delta:
    aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
    dimensions:
    - default: default
      name: service.namespace
    - default: default
      name: deployment.environment
    - name: o11y.collector.id
    - name: service.version
    dimensions_cache_size: 100000
    enable_exp_histogram: true
    latency_histogram_buckets:
    - 100us
    - 1ms
    - 2ms
    - 6ms
    - 10ms
    - 50ms
    - 100ms
    - 250ms
    - 500ms
    - 1000ms
    - 1400ms
    - 2000ms
    - 5s
    - 10s
    - 20s
    - 40s
    - 60s
    metrics_exporter: o11yclickhousemetrics
    metrics_flush_interval: 60s
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
service:
  extensions:
  - o11y_health_check
  - pprof
  pipelines:
    logs:
      exporters:
      - clickhouselogsexporter
      - o11ymeter
      processors:
      - batch
      receivers:
      - otlp
    metrics:
      exporters:
      - o11yclickhousemetrics
      - o11ymeter
      processors:
      - batch
      receivers:
      - otlp
    metrics/meter:
      exporters:
      - o11yclickhousemeter
      processors:
      - batch/meter
      receivers:
      - o11ymeter
    traces:
      exporters:
      - clickhousetraces
      - o11ymeter
      processors:
      - o11yspanmetrics/delta
      - batch
      receivers:
      - otlp
  telemetry:
    logs:
      encoding: json
