databases:
- databaseName: o11y
  ipAllowList: []
  name: o11y-metastore-postgres
  plan: free
  postgresMajorVersion: "16"
  user: o11y
services:
- disk:
    mountPath: /var/lib/clickhouse-keeper
    name: o11y-telemetrykeeper-clickhousekeeper-0-data
    sizeGB: 5
  dockerContext: configs/telemetrykeeper
  dockerfilePath: configs/telemetrykeeper/Dockerfile
  name: o11y-telemetrykeeper-clickhousekeeper-0
  plan: standard
  runtime: docker
  type: pserv
- disk:
    mountPath: /var/lib/clickhouse
    name: o11y-telemetrystore-clickhouse-0-0-data
    sizeGB: 20
  dockerContext: configs/telemetrystore
  dockerfilePath: configs/telemetrystore/Dockerfile
  envVars:
  - key: CLICKHOUSE_SKIP_USER_SETUP
    value: "1"
  - key: CLICKHOUSE_CONFIG
    value: /etc/clickhouse-server/config.yaml
  - fromService:
      name: o11y-telemetrykeeper-clickhousekeeper-0
      property: host
      type: pserv
    key: DEPENDENCY_LINK_0
  name: o11y-telemetrystore-clickhouse-0-0
  plan: standard
  runtime: docker
  type: pserv
- dockerContext: configs/ingester
  dockerfilePath: configs/ingester/Dockerfile
  envVars:
  - fromService:
      name: o11y-telemetrystore-clickhouse-0-0
      property: host
      type: pserv
    key: DEPENDENCY_LINK_0
  name: o11y-ingester-0
  plan: standard
  runtime: docker
  type: pserv
- envVars:
  - key: HANZO_SQLSTORE_PROVIDER
    value: postgres
  - key: HANZO_TELEMETRYSTORE_CLICKHOUSE_DSN
    value: tcp://o11y-telemetrystore-clickhouse-0-0:9000
  - key: HANZO_TELEMETRYSTORE_PROVIDER
    value: clickhouse
  - fromDatabase:
      name: o11y-metastore-postgres
      property: connectionString
    key: HANZO_SQLSTORE_POSTGRES_DSN
  - fromService:
      name: o11y-telemetrystore-clickhouse-0-0
      property: host
      type: pserv
    key: DEPENDENCY_LINK_0
  healthCheckPath: /api/v1/health
  image:
    url: ghcr.io/hanzoai/o11y:latest
  name: o11y-o11y
  plan: standard
  runtime: image
  type: web
- dockerCommand: |
    /bin/sh -c /o11y-otel-collector migrate bootstrap --clickhouse-dsn=$CLICKHOUSE_DSN
      && /o11y-otel-collector migrate sync up --clickhouse-dsn=$CLICKHOUSE_DSN
      && /o11y-otel-collector migrate async up --clickhouse-dsn=$CLICKHOUSE_DSN
  envVars:
  - key: CLICKHOUSE_DSN
    value: tcp://o11y-telemetrystore-clickhouse-0-0:9000
  - fromService:
      name: o11y-telemetrystore-clickhouse-0-0
      property: host
      type: pserv
    key: DEPENDENCY_LINK_0
  image:
    url: ghcr.io/hanzoai/otel-collector:latest
  name: o11y-schema-migrator
  plan: standard
  preDeployCommand: /o11y-otel-collector migrate ready --clickhouse-dsn=${CLICKHOUSE_DSN}
    --timeout 60s
  runtime: image
  type: worker
