configs:
  clickhouse-config:
    content: |
      <clickhouse>
        <remote_servers>
            <cluster>
                <shard>
                    <replica>
                        <host>clickhouse</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </cluster>
        </remote_servers>
        <zookeeper>
            <node>
                <host>zookeeper</host>
                <port>2181</port>
            </node>
        </zookeeper>
        <macros>
          <shard>01</shard>
          <replica>01</replica>
        </macros>
      </clickhouse>
  otel-collector-config:
    content: |
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

      processors:
        batch:
          send_batch_size: 10000
          send_batch_max_size: 11000
          timeout: 10s
        resourcedetection:
          # Using OTEL_RESOURCE_ATTRIBUTES envvar, env detector adds custom labels.
          detectors: [env, system]
          timeout: 2s
        signozspanmetrics/delta:
          metrics_exporter: signozclickhousemetrics
          metrics_flush_interval: 60s
          latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 50ms, 100ms, 250ms, 500ms, 1000ms, 1400ms, 2000ms, 5s, 10s, 20s, 40s, 60s ]
          dimensions_cache_size: 100000
          aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
          enable_exp_histogram: true
          dimensions:
            - name: service.namespace
              default: default
            - name: deployment.environment
              default: default
            - name: signoz.collector.id
            - name: service.version
            - name: browser.platform
            - name: browser.mobile
            - name: k8s.cluster.name
            - name: k8s.node.name
            - name: k8s.namespace.name
            - name: host.name
            - name: host.type
            - name: container.name

      exporters:
        clickhousetraces:
          datasource: tcp://clickhouse:9000/signoz_traces
          low_cardinal_exception_grouping: $${env:LOW_CARDINAL_EXCEPTION_GROUPING}
          use_new_schema: true
        signozclickhousemetrics:
          dsn: tcp://clickhouse:9000/signoz_metrics
        clickhouselogsexporter:
          dsn: tcp://clickhouse:9000/signoz_logs
          timeout: 10s
          use_new_schema: true

      service:
        telemetry:
          logs:
            encoding: json
        pipelines:
          traces:
            receivers: [otlp]
            processors: [signozspanmetrics/delta, batch]
            exporters: [clickhousetraces]
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [signozclickhousemetrics]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [clickhouselogsexporter]
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    configs:
      - source: clickhouse-config
        target: /etc/clickhouse-server/config.d/config.xml
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'
    tty: true
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - 0.0.0.0:8123/ping
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - zookeeper
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
  zookeeper:
    image: signoz/zookeeper:3.7.1
    container_name: zookeeper
    ports:
      - '127.0.0.1:2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test:
        - CMD-SHELL
        - curl -s -m 2 http://localhost:8080/commands/ruok | grep error | grep null
      interval: 30s
      timeout: 5s
      retries: 3
  schema-migrator-sync:
    image: signoz/signoz-schema-migrator:v0.129.9
    container_name: schema-migrator-sync
    command:
      - sync
      - --cluster-name=cluster
      - --dsn=tcp://clickhouse:9000
      - --replication=true
      - --up=
    depends_on:
      clickhouse:
        condition: service_healthy
    restart: on-failure
  otel-collector:
    image: signoz/signoz-otel-collector:v0.129.9
    container_name: signoz-otel-collector-dev
    command:
      - --config=/etc/otel-collector-config.yaml
      - --feature-gates=-pkg.translator.prometheus.NormalizeName
    configs:
      - source: otel-collector-config
        target: /etc/otel-collector-config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
    ports:
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP HTTP receiver
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - localhost:13133
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    depends_on:
      clickhouse:
        condition: service_healthy
  signoz:
    image: signoz/signoz:${VERSION:-v0.101.0}
    container_name: signoz
    ports:
      - '8080:8080'
    volumes:
      - signoz-data:/var/lib/signoz/
    environment:
      - SIGNOZ_ALERTMANAGER_PROVIDER=signoz
      - SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - SIGNOZ_SQLSTORE_SQLITE_PATH=/var/lib/signoz/signoz.db
      - DASHBOARDS_PATH=/root/config/dashboards
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=true
      - DEPLOYMENT_TYPE=docker-standalone-amd
      - DOT_METRICS_ENABLED=true
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - localhost:8080/api/v1/health
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - clickhouse
volumes:
  clickhouse-data:
  signoz-data:
