clickhouse:
  enabled: true
  fullnameOverride: signoz-telemetrystore-clickhouse
  image:
    repository: clickhouse/clickhouse-server
    tag: 25.5.6
  layout:
    replicasCount: 0
    shardsCount: 1
  persistence:
    enabled: true
    size: 100Gi
    storageClass: gp3
  resources:
    limits:
      cpu: "4"
      memory: 8Gi
    requests:
      cpu: "2"
      memory: 4Gi
  zookeeper:
    enabled: true
    fullnameOverride: signoz-telemetrykeeper-zookeeper
    image:
      repository: signoz/zookeeper
      tag: 3.7.1
    replicaCount: 1
fullnameOverride: signoz
otelCollector:
  enabled: true
  image:
    repository: signoz/signoz-otel-collector
    tag: latest
  name: ingester
  ports:
    otlp:
      containerPort: 4317
      enabled: true
      protocol: TCP
      servicePort: 4317
    otlp-http:
      containerPort: 4318
      enabled: true
      protocol: TCP
      servicePort: 4318
  replicaCount: 1
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
postgresql:
  auth:
    database: signoz
    password: signoz
    username: signoz
  enabled: true
  fullnameOverride: signoz-metastore-postgres
  image:
    repository: postgres
    tag: 16
signoz:
  env:
    SIGNOZ_SQLSTORE_POSTGRES_DSN: postgres://signoz:signoz@signoz-metastore-postgres:5432/signoz?sslmode=disable
    SIGNOZ_SQLSTORE_PROVIDER: postgres
    SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN: tcp://signoz-telemetrystore-clickhouse:9000
    SIGNOZ_TELEMETRYSTORE_PROVIDER: clickhouse
  image:
    repository: signoz/signoz
    tag: latest
  name: signoz
  nodeSelector:
    node-role.kubernetes.io/observability: ""
  replicaCount: 1
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  service:
    internalPort: 8085
    opampPort: 4320
    port: 8080
    type: ClusterIP
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: signoz
telemetryStoreMigrator:
  enabled: true
  name: signoz-telemetrystore-migrator
