apiVersion: v1alpha1
metadata:
  name: signoz
spec:
  deployment:
    flavor: compose
    mode: docker
  infrastructure:
    enabled: false
    provider: aws
  ingester:
    spec:
      cluster:
        replicas: 1
      config: {}
      enabled: true
      image: signoz/signoz-otel-collector:latest
      version: latest
    status:
      addresses:
        otlp: null
      config: {}
  metastore:
    kind: postgres
    spec:
      cluster:
        replicas: 1
      config: {}
      enabled: true
      image: postgres:16
      version: "16"
    status:
      addresses:
        dsn: null
      config: {}
  signoz:
    spec:
      cluster:
        replicas: 1
      config: {}
      enabled: true
      image: signoz/signoz:latest
      version: latest
    status:
      addresses:
        apiserver: null
        opamp: null
      config: {}
  telemetrykeeper:
    kind: clickhousekeeper
    spec:
      cluster:
        replicas: 1
      config: {}
      enabled: true
      image: clickhouse/clickhouse-keeper:25.5.6
      version: 25.5.6
    status:
      addresses:
        client: null
        raft: null
      config: {}
  telemetrystore:
    kind: clickhouse
    spec:
      cluster:
        replicas: 0
        shards: 1
      config: {}
      enabled: true
      image: clickhouse/clickhouse-server:25.5.6
      version: 25.5.6
    status:
      addresses:
        tcp: null
      config: {}
