services:
  clickhouse-1:
    extends:
      service: clickhouse-1
      file: ../generic/docker-compose.yaml
    volumes:
      - clickhouse-1:/var/lib/clickhouse/
      - ./configs/clickhouse/cluster.ha.xml:/etc/clickhouse-server/config.d/cluster.xml
  clickhouse-2:
    container_name: signoz-clickhouse-2
    extends:
      service: clickhouse-1
      file: ../generic/docker-compose.yaml
    volumes:
      - clickhouse-2:/var/lib/clickhouse/
      - ./configs/clickhouse/cluster.ha.xml:/etc/clickhouse-server/config.d/cluster.xml

  clickhouse-3:
    container_name: signoz-clickhouse-3
    extends:
      service: clickhouse-1
      file: ../generic/docker-compose.yaml
    volumes:
      - clickhouse-3:/var/lib/clickhouse/
      - ./configs/clickhouse/cluster.ha.xml:/etc/clickhouse-server/config.d/cluster.xml
  zookeeper-2:
    extends:
      service: zookeeper-1
      file: ../generic/docker-compose.yaml
    container_name: signoz-zookeeper-2
    # ports:
    #   - "2182:2181"
    #   - "2889:2888"
    #   - "3889:3888"
    volumes:
      - zookeeper-2:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper-1:2888:3888,0.0.0.0:2888:3888,zookeeper-3:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ZOO_PROMETHEUS_METRICS_PORT_NUMBER=9141
  zookeeper-3:
    extends:
      service: zookeeper-1
      file: ../generic/docker-compose.yaml
    container_name: signoz-zookeeper-3
    # ports:
    #   - "2182:2181"
    #   - "2889:2888"
    #   - "3889:3888"
    volumes:
      - zookeeper-3:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper-1:2888:3888,zookeeper-2:2888:3888,0.0.0.0:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ZOO_PROMETHEUS_METRICS_PORT_NUMBER=9141

volumes:
  clickhouse-1:
    name: signoz-clickhouse
  clickhouse-2:
    name: signoz-clickhouse-2
  clickhouse-3:
    name: signoz-clickhouse-3
  sqlite:
    name: signoz-sqlite
  zookeeper-1:
    name: signoz-zookeeper-1
  zookeeper-2:
    name: signoz-zookeeper-2
  zookeeper-3:
    name: signoz-zookeeper-3
